const lebensWeisheiten = [
    "Wenn Chancen nicht anklopfen, baue eine Tür!",
    "Manchmal hält man alle Asse in der Hand - doch das Leben spielt Schach.",
    "In jeder Minute Ärger verlieren wir 60 Sekunden Lebensfreude.",
    "Du erfährst das, was du glaubst.",
    "Wer für seine Beschränkungen kämpft, wird sie behalten.",
    "Man kann nicht dankbar und unglücklich zugleich sein.",
    "Wer ein guter Mensch ist, verliert keine Freunde. Sie verlieren dich.",
    "Der Weg aus Angst heraus geht immer durch Angst hindurch.",
    "Wem du die Schuld gibst, dem gibst du die Macht.",
    "Innen muss etwas brennen, damit außen etwas leuchten kann.",
    "Es gibt Feststeller und Absteller.",
    "Die Tat unterscheidet das Ziel vom Traum.",
    "Vorne ist immer da, wo sich keiner auskennt.",
    "Bessere Aussichten schaffen bessere Einsichten.",
    "Für gute Gewohnheiten bezahlen Sie in der Gegenwart, für schlechte in der Zukunft.",
    "Oft fühlt sich das Leben wie ein Test an, für den man nicht gelernt hat.",
    "Menschen sind aggressiver, wenn sie sich unsicher fühlen.",
    "Wer immer in Eile ist, begegnet niemandem - nicht einmal sich selbst.",
    "Es gibt mehr Menschen, die aufgeben als jene, die scheitern.",
    "Lebe dein Leben, nicht das der anderen.",
    "Kleine Schritte sind besser als keine Schritte.",
    "Sei die Veränderung, die du in der Welt sehen willst.",
    "Wer langsam geht, kommt auch zum Ziel.",
    "Achte auf deine Gedanken, denn sie sind der Anfang deiner Taten.",
    "Ob ein Mensch klug ist, erkennt man an seinen Antworten; die Weisheit an seinen Fragen.",
    "Wenn der Klügere stets nachgibt, regieren die Dummen die Welt.",
    "Arroganz ist das Selbstbewusstsein des Minderwertigkeitskomplexes.",
    "EIN Tag oder ERSTER Tag - du entscheidest!",
    "Man sieht sich immer zwei Mal im Leben.",
    "Unsere Sichtweise entscheidet über unsere Zufriedenheit.",
    "Wenn ein Drache steigen will, muss er gegen den Wind fliegen.",
    "Wenn sich niemand über dein Werk aufregt, ist es bedeutungslos.",
    "Bevor du mit dem Kopf durch die Wand willst, frage dich: Was will ich im Nebenzimmer?",
    "Nichts ist hilfreicher als eine Herausforderung, um das Beste in einem Menschen hervorzubringen.",
    "Auf Dauer nimmt die Seele die Farbe deiner Gedanken an.",
    "Das höchste Gut ist die Harmonie der Seele mit sich selbst.",
    "Begeisterung ist Dünger für das Gehirn.",
    "Wenn du es nicht versuchst, wirst du nie wissen, ob du es kannst.",
    "Das Schönste, was wir erleben können, ist das Geheimnisvolle.",
    "Denke nicht so oft an das, was dir fehlt, sondern an das, was du hast.",
    "Der größte Feind des Fortschritts ist nicht der Irrtum, sondern die Trägheit.",
    "Lebe als würdest du morgen sterben. Lerne als würdest du für immer leben.",
    "Ziel des Lebens ist es nicht, ein erfolgreicher Mensch zu sein - sondern ein wertvoller.",
    "In der Wut verliert der Mensch seine Intelligenz.",
    "Der wahre Beruf des Menschen ist, zu sich selbst zu kommen.",
    "Auch im Alphabet kommt Anstrengung vor Erfolg.",
    "Wer sich selbst alles zutraut, wird andere übertreffen.",
    "Wer einen Misserfolg als kleinen Umweg betrachtet, verliert nie sein Ziel aus den Augen.",
    "Auch eine Enttäuschung bedeutet einen Schritt vorwärts.",
    "Leiden, Irrtum und Widerstandskraft halten das Leben lebendig.",
    "Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.",
    "Sag einer Person, dass sie mutig ist, und du hilfst ihr es zu werden.",
    "Was du liebst, lass frei. Kommt es zurück, gehört es dir für immer.",
    "Neue Wege entstehen dadurch, dass man sie geht.",
    "Ohne Leiden bildet sich kein Charakter.",
    "Erfahrung ist der beste Lehrmeister. Nur das Schulgeld ist teuer.",
    "Mit dem Wissen wächst der Zweifel.",
    "Arbeit ist das beste Mittel gegen Verzweiflung.",
    "Eine Wahrheit kann erst wirken, wenn der Empfänger für sie reif ist.",
    "Der Kopf ist rund, damit das Denken die Richtung ändern kann.",
    "Jedermann klagt über sein Gedächtnis, niemand über seinen Verstand.",
    "Wer Stroh im Kopf hat, fürchtet den Funken der Wahrheit.",
    "Heute kennt man von allem den Preis, von nichts den Wert.",
    "Der unzufriedene Mensch findet keinen bequemen Stuhl.",
    "Dumme Gedanken hat jeder, aber der Weise verschweigt sie.",
    "Es gibt nur einen Weg, um Kritik zu vermeiden: Nichts tun, nichts sagen, nichts sein.",
    "Ein bisschen mehr Humor, täterätete uns allen ganz gut.",
    "Wenn dich das Leben in die Knie zwingt - tanze Limbo!",
    "Nicht jeder, der aus dem Rahmen fällt, war vorher im Bilde.",
    "Wer mit beiden Beinen auf dem Boden steht, kommt nicht vorwärts.",
    "Wer nie vom Weg abkommt, bleibt auf der Strecke.",
    "Wer nach allen Seiten offen ist, ist meistens nicht ganz dicht.",
    "Niemand, der sein Bestes gegeben hat, hat es später bereut.",
    "Das Leben ist zu kurz für irgendwann.",
    "Das kalte Wasser wird nicht wärmer, wenn du später springst.",
    "Wer sich selbst alles zutraut, wird andere übertreffen.",
    "Ein Diamant ist ein Stück Kohle, das Ausdauer hatte.",
    "Schmerz ist vergänglich, Erfolg bleibt für immer.",
    "Wer nur mit dem Herzen gut sieht, ist blind.",
    "Everybodys Darling is Everybodys Depp.",
    "Ich hatte in meinem Leben schon eine Menge Nahidioterfahrungen.",
    "Wenn das Leben ein Theater ist: Such dir die Rolle aus, die Spaß macht!",
    "Dummheit ist auch eine natürliche Begabung.",
    "Auch Umwege erweitern unseren Horizont.",
    "Liebe dich selbst, als ob dein Leben davon abhängt.",
    "Wer eine hilfreiche Hand sucht, findet sie am unteren Ende seines Armes.",
    "Alter schützt vor Liebe nicht, aber Liebe vor dem Altern!",
    "Wenn dir das Leben einen Geburtstag schenkt, mach ein Fest daraus!",
    "Kümmere dich nicht um die Zahl der Jahre, sondern darum, dass die Jahre zählen!",
    "Jeder Geburtstag ist die Erinnerung daran, die Vergangenheit zu akzeptieren, die Gegenwart zu lieben und sich auf die Zukunft zu freuen.",
    "Alt werden, das ist Gottes Gunst. Jung bleiben, das ist Lebenskunst.",
    "Je älter du wirst, desto mehr erkennst du: Es geht nicht darum, wie du aussiehst oder was du besitzt. Sondern um die Persönlichkeit, die du geworden bist.",
    "Man ist in den besten Jahren, wenn man die guten hinter sich hat.",
    "Es ist nicht Lebenslänge, sondern die Lebenstiefe, die zählt.",
    "Jeder, der sich die Fähigkeit erhält, Schönes zu erkennen, wird nie alt werden.",
    "Der Apfel lehrt uns zu begreifen, die Besten - das sind die Reifen.",
    "Der höchste Genuss besteht in der Zufriedenheit mit sich selbst.",
    "Wer hohe Türme bauen will, muss lange beim Fundament verweilen.",
    "Fange nie an aufzuhören - und höre nie auf anzufangen.",
    "Mut steht am Anfang des Handelns, Glück am Ende.",
    "Hindernisse und Schwierigkeiten sind Stufen, auf denen wir in die Höhe steigen.",
    "Liebe ist nur ein Wort - bis jemand kommt und ihm eine Bedeutung gibt.",
    "Entfernung kann nur Körper trennen, aber niemals Herzen.",
    "Wenn du still bist, verstehen dich nur Menschen, die dich fühlen.",
    "Der Liebe zu begegnen, ohne sie zu suchen, ist der einzige Weg, um sie zu finden.",
    "Nicht die Schönheit entscheidet, wen wir lieben, sondern die Liebe entscheidet, wen wir schön finden.",
    "Liebe ist nicht alles, was wir brauchen. Aber wir brauchen sie, um alles zu haben.",
    "Kleider machen Leute, aber das Herz macht den Menschen.",
    "Bei der falschen Person kannst du nichts richtig machen. Bei der richtigen Person kannst du nichts falsch machen.",
    "Wenn dir jemand nicht mehr aus dem Kopf geht, dann gehört er in dein Herz.",
    "Liebe ist wie ein Vollbad. Einlassen, warm halten & darin baden, bis man schrumpelig wird.",
    "Wenn wir jemanden wirklich lieben, können wir genau der Mensch sein, der wir wirklich sind.",
    "Echte Liebe braucht keine großen Gesten. Sie zeigt sich in den kleinsten Blicken und Berührungen.",
    "Solange man neugierig ist, kann einem das Alter nichts anhaben.",
    "Das einzig Wichtige im Leben sind die Spuren der Liebe, die wir hinterlassen, wenn wir gehen.",
    "Die Vernunft kann nur reden. Es ist die Liebe, die singt.",
    "Ein Tropfen Liebe ist mehr als ein Ozean Verstand.",
    "Liebe ist ein Glas, das zerbricht, wenn man es zu unsicher oder zu fest fasst.",
    "Was du liebst, lass frei. Kommt es zurück, gehört es dir für immer.",
    "Liebe ist kein Solo. Liebe ist ein Duett. Schwindet sie bei einem, verstummt das Lied.",
    "Die Summe unseres Lebens sind die Stunden, wo wir lieben.",
    "Freundschaft ist verstehen ohne Worte.",
    "Falsche Freunde glauben Gerüchten. Echte Freunde glauben an Dich.",
    "Es gibt Freunde im Leben und es gibt Freunde fürs Leben.",
    "Freunde sind die Familie, die wir uns selbst aussuchen.",
    "Freundschaft ist Heimat unabhängig vom Ort.",
    "Freundschaft ist wie Liebe - nur mit Verstand.",
    "Ein bisschen Freundschaft ist mir mehr wert als die Bewunderung der Welt.",
    "Freundschaft muss nicht perfekt sein. Nur echt.",
    "Freundschaft wärmt die Seele, wenn sich die Sonne versteckt.",
    "Wahre Freunde stolpern in dein Leben und bleiben mit voller Absicht.",
    "Mit den richtigen Menschen im Rücken kann dich nichts umwerfen.",
    "Freundschaft ohne Vertrauen ist wie eine Blume ohne Duft.",
    "Freunde fragen nicht nach deinem Weg, sondern gehen ihn einfach mit dir.",
    "Freundschaft, das ist eine Seele in zwei Körpern.",
    "Einen sicheren Freund erkennt man in unsicherer Sache.",
    "Die besten Freunde sind diejenigen, mit denen man über dieselben Dinge schweigen kann.",
    "Lebensfreude ist ein Maßanzug: Unglückliche Menschen versuchen, den eines anderen zu tragen.",
    "Du kannst die Zukunft verändern mit dem, was du heute tust.",
    "Scheitern ist nicht das Gegenteil von Erfolg. Es ist ein Teil davon.",
    "Mach es, bevor du bereust, es nicht getan zu haben!",
    "Wenn du fliegen willst, musst du loslassen, was dich runterzieht.",
    "Wenn du aufgeben willst, denk daran, warum du angefangen hast.",
    "Du lächelst - und die Welt verändert sich.",
    "Dreh dein Gesicht zur Sonne, dann fallen die Schatten hinter dich.",
    "Glück ist ein Parfum, das du nicht auf andere sprühen kannst, ohne selbst ein paar Tropfen abzubekommen.",
    "Die glücklichsten Menschen haben nicht unbedingt das Beste. Aber sie machen das Beste aus dem, was sie haben.",
    "Die schönsten Momente kann man nicht erzwingen, sie entstehen zufällig auf dem Weg.",
    "Niemand kriegt beim ersten Mal alles richtig hin. Was uns ausmacht, ist, wie wir aus unseren Fehlern lernen.",
    "Ein Optimist findest immer einen Weg. Ein Pessimist findet immer eine Sackgasse.",
    "Es gibt nur zwei Tage in deinem Leben, an denen du nichts ändern kannst: Der eine ist gestern und der andere ist morgen.",
    "In drei Worten kann ich alles zusammenfassen, was ich über das Leben gelernt: Es geht weiter.",
    "Zufriedenheit bedeutet nicht alles zu haben, sondern das Beste aus allem zu machen.",
    "Wem genug zu wenig ist, dem ist nichts genug.",
    "Das Vergleichen ist das Ende des Glücks und der Anfang der Unzufriedenheit.",
    "Es ist schwer, das Glück in uns zu finden. Aber es ist ganz unmöglich, es anderswo zu finden.",
    "Man ist nur unglücklich, weil man Zeit hat, zu überlegen, ob man unglücklich ist oder nicht.",
    "Das Glück Deines Lebens hängt von der Beschaffenheit Deiner Gedanken ab.",
    "Wenn man glücklich ist, soll man nicht noch glücklicher sein wollen.",
    "Das Glück des Lebens besteht nicht darin, weniger Schwierigkeiten zu haben, sondern sie alle glorreich zu überwinden.",
    "Lasse nie zu, dass du jemandem begegnest, der nicht nach der Begegnung mit dir glücklicher ist.",
    "Nicht das Beginnen wird belohnt, sondern einzig und allein das Durchhalten.",
    "Ausdauer wird früher oder später belohnt - meistens aber später.",
    "Sorgen sind wie Gespenster: Wer sich nicht vor ihnen fürchtet, dem können sie nichts anhaben.",
    "Es ist besser, ein einziges kleines Licht anzuzünden, als die Dunkelheit zu verfluchen.",
    "Man spürt selten, was Glück ist, aber man weiß meistens, was Glück war.",
    "Wer will, findet Wege, wer nicht will, findet Gründe.",
    "Der sicherste Weg zum Erfolg ist immer, es doch noch einmal zu versuchen.",
    "Unsere größte Schwäche liegt im Aufgeben. Der sicherste Weg zum Erfolg ist immer, es noch einmal zu versuchen.",
    "Ich habe aus meinen Rückschlägen oft mehr gelernt als aus meinen Erfolgen.",
    "Nicht der Schnellste und Stärkste siegt, sondern der, der denkt, dass er es kann.",
    "Es gibt keinen Misserfolg. Entweder du hast Erfolg oder du lernst.",
    "Man lernt eine Zeile von einem Sieg und ein Buch aus einer Niederlage.",
    "Die Lösung ist immer einfach, man muss sie nur finden.",
    "Alle Dinge sind schwer bevor sie leicht werden.",
    "Jeder Erfolg, den man erzielt, schafft einen Feind. Man muss mittelmäßig sein, wenn man beliebt sein will.",
    "Habe keine Angst, das Gute aufzugeben, um das Großartige zu erreichen.",
    "Wer aufhört, besser werden zu wollen, hört auf, gut zu sein.",
    "Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.",
    "Es ist ein großer Vorteil im Leben, die Fehler, aus denen man lernen kann, möglichst früh zu begehen.",
    "Denken ist die schwerste Arbeit, die es gibt. Das ist wahrscheinlich auch der Grund, warum sich so wenige Leute damit beschäftigen.",
    "Wer nicht von der Vergangenheit lernt, wird von der Zukunft bestraft.",
    "Ein Gramm Wissen ist mir lieber, als einhundert Tonnen Meinung.",
    "Der Nachteil der Intelligenz besteht darin, dass man ununterbrochen gezwungen ist, dazuzulernen.",
    "Der Mensch soll lernen, nur die Ochsen büffeln.",
    "Bildung ist das, was übrig bleibt, wenn wir vergessen, was wir gelernt haben.",
    "Du lernst nicht zu laufen, indem du Regeln folgst. Du lernst es, indem du hinfällst.",
    "Gerade Leute, die nichts lernen, lernen auch nichts daraus, dass sie nichts gelernt haben.",
    "Ein Buch ist ein Spiegel, wenn ein Affe hineinsieht, so kann kein Apostel herausgucken.",
    "Lernen ist wie Rudern gegen den Strom. Hört man damit auf, treibt man zurück.",
    "Wer einen Fehler gemacht hat und ihn nicht korrigiert, begeht einen zweiten.",
    "Ein Kopf ohne Gedächtnis ist eine Festung ohne Besatzung.",
    "Eine Investition in Wissen bringt noch immer die besten Zinsen.",
    "Von dem was wir noch nicht wissen können wir am meisten lernen.",
    "Auch das schlechteste Buch hat seine gute Seite: die letzte.",
    "Stille ist die Sprache der Weisheit, Lärm die Stimme der Unwissenheit.",
    "Der größte Reichtum ist ein zufriedenes Herz.",
    "In der Dunkelheit der Nacht beginnen die Sterne zu leuchten.",
    "Deine größten Narben werden zu deinen stärksten Geschichten.",
    "Die wertvollsten Schätze liegen tief verborgen in deinem Inneren.",
    "Die tiefsten Gedanken sind wie ein Ozean - still, tief und unergründlich.",
    "Die Wahrheit ist der beste Wegweiser in der Welt des Irrtums.",
    "Deine Gedanken formen die Welt, in der du lebst.",
    "Nicht alles, was gebrochen ist, kann repariert werden, aber man kann in den Rissen wunderschöne Muster finden.",
    "Das Universum ist ein Buch, das nur den offenen Geistlichen enthüllt wird.",
    "Vergiss nie, dass du auch ein Stern am Himmel des Lebens bist.",
    "Die Einsamkeit ist nicht der Mangel an Gesellschaft, sondern der Mangel an tiefer Verbindung.",
    "Erfolg ist wie ein Schatten: Je mehr du ihn jagst, desto weiter entfernt scheint er zu sein.",
    "Das größte Geschenk, das du geben kannst, ist deine Zeit und Aufmerksamkeit.",
    "Dein wahres Selbst liegt jenseits der Maske, die du der Welt zeigst.",
    "Der Sinn des Lebens liegt in den Beziehungen, die wir aufbauen.",
    "Nichts ist ewig, aber die Erinnerung an die Liebe und die guten Taten bleibt.",
    "Wahre Stärke liegt in der Fähigkeit, sanft zu sein.",
    "Die Wahrheit ist wie eine Leiter - manchmal ist sie steil, aber sie führt immer nach oben.",
    "Deine Reise ist einzigartig, also vergleiche sie nicht mit anderen.",
    "Das Wunder liegt im Hier und Jetzt verborgen.",
    "Die größte Weisheit liegt im Zuhören, nicht im Sprechen.",
    "Ein starker Mensch steht auf und kämpft, während ein noch stärkerer Mensch aufsteht und umarmt.",
    "Der Wert deines Lebens liegt nicht in der Länge, sondern in der Tiefe.",
    "Wahre Freiheit liegt in der Akzeptanz deiner selbst.",
    "Deine Gedanken sind wie Wolken - lass sie vorbeiziehen, ohne an ihnen festzuhalten.",
    "Glück entsteht, wenn du Frieden mit deiner Vergangenheit machst, die Gegenwart akzeptierst und in die Zukunft vertraust.",
    "Das größte Geschenk, das du jemandem geben kannst, ist Liebe, aber vergiss nicht, sie zuerst dir selbst zu schenken.",
    "Erfolg beginnt am Ende deiner Komfortzone.",
    "Wahre Größe liegt in der Freundlichkeit und Demut, nicht in der Macht oder dem Besitz.",
    "Deine Geduld wird belohnt, wenn du wartest, ohne zu erwarten.",
    "Jeder Abschied ist eine Chance für einen neuen Anfang.",
    "Das Leben ist wie ein Puzzle - manchmal passen die Stücke nicht, aber sie ergeben trotzdem ein wunderschönes Bild.",
    "Die tiefsten Einsichten kommen in Momenten der Stille.",
    "Die größten Entdeckungen geschehen außerhalb deiner Komfortzone.",
    "Schmerz ist der Katalysator für Wachstum und Veränderung.",
    "Du kannst den Wind nicht ändern, aber du kannst die Segel neu setzen.",
    "Das Leben ist wie Musik - die Noten sind nur so schön wie die Stille dazwischen.",
    "In der Ruhe des Wassers spiegelt sich die Klarheit des Geistes.",
    "Liebe ist die universelle Sprache des Herzens.",
    "Die wertvollsten Schätze sind oft in den einfachsten Dingen des Lebens verborgen.",
    "Erfolg ist, wenn du fällst und wieder aufstehst, nicht wenn du nie gefallen bist.",
    "In der Dunkelheit erkennst du den Wert des Lichts.",
    "Die größte Macht liegt in der Selbstbeherrschung.",
    "Die Zeit heilt nicht alles, aber sie lehrt uns, mit dem Schmerz zu leben.",
    "Die Wahrheit liegt oft in der Stille zwischen den Worten.",
    "Dein Herz kennt den Weg, auch wenn dein Verstand ihn nicht versteht.",
    "Das Glück beginnt mit der Entscheidung, dankbar zu sein.",
    "Jeder Tag ist ein neues Leben, jede Nacht ein neuer Traum.",
    "Das Leben ist eine Reise, keine Destination.",
    "Das Geheimnis des Glücks liegt im Geben, nicht im Nehmen.",
    "Nichts kann dich verletzen, ohne deine Zustimmung.",
    "Das Leben ist wie ein Buch - manchmal musst du umblättern, um zu sehen, was als Nächstes passiert.",
    "Die wahre Schönheit liegt im Wesen, nicht im Aussehen.",
    "Die größte Abenteuerlust liegt in der Neugierde des Geistes.",
    "Das Lächeln, das du aussendest, kehrt zu dir zurück.",
    "Jedes Problem birgt auch eine Lösung in sich.",
    "Deine Seele ist der Spiegel deines Herzens.",
    "Die größte Stärke liegt in der Akzeptanz deiner Schwächen.",
    "Dein Herz kennt den Weg - höre auf seine Weisheit.",
    "Das Universum ist in einem Sandkorn enthalten.",
    "Die größte Freiheit liegt im Loslassen von Erwartungen.",
    "Das Leben ist ein Tanz - manchmal langsam, manchmal wild, aber immer schön.",
    "Deine Träume sind die Baupläne für deine Zukunft.",
    "Liebe ist der einzige Reichtum, der sich vermehrt, wenn man ihn teilt.",
    "Die größte Lüge ist die, die du dir selbst erzählst.",
    "Nichts ist unveränderlich außer der Veränderung selbst.",
    "Die schönsten Farben entstehen im Dunkeln.",
    "Erfolg ist, wenn du tust, was du liebst, und anderen damit hilfst.",
    "Jede Begegnung hinterlässt eine Spur, auch wenn du sie nicht siehst.",
    "Die größte Freude liegt im Einfachen.",
    "Das Glück liegt im Gleichgewicht.",
    "Die größte Freiheit ist die Freiheit von deinem eigenen Geist.",
    "Die Zeit heilt, aber die Narben erinnern.",
    "Wahre Stärke liegt im Loslassen.",
    "Deine Intuition ist dein bester Ratgeber.",
    "Erfolg ist die Summe kleiner Anstrengungen, jeden Tag wiederholt.",
    "Die beste Reise ist die Reise zu sich selbst.",
    "Viele Dinge, die wir uns wünschen, sind in Reichweite, wenn wir den Mut haben, danach zu greifen.",
    "Du bist nie zu alt, um zu lernen, und nie zu jung, um zu führen.",
    "Wahre Schönheit liegt im Charakter, nicht im Aussehen.",
    "Das größte Geschenk ist Zeit - verbringe sie weise.",
    "Dein Herz kennt den Weg, folge ihm.",
    "Das Leben ist wie ein Atemzug - kurz, aber wertvoll.",
    "Die besten Geschichten beginnen mit einem Sprung ins Unbekannte.",
    "Die größte Veränderung beginnt mit einem kleinen Schritt.",
    "Echte Liebe besteht darin, bedingungslos zu lieben, ohne Bedingungen zu stellen.",
    "Der größte Reichtum ist, das Leben zu lieben, das du lebst.",
    "Nichts ist konstant außer der Veränderung.",
    "In der Stille hörst du die Weisheit der Welt.",
    "Die größte Belohnung liegt im Teilen, nicht im Besitzen.",
    "Die wahren Helden sind diejenigen, die anderen ohne Erwartung helfen.",
    "Wahre Freiheit liegt im Loslassen von Erwartungen.",
    "Das Leben ist ein Tanz - finde deinen Rhythmus.",
    "Erfolg ist, wenn du anderen ein Lächeln schenkst.",
    "Das Leben ist wie ein Gemälde - jeder Pinselstrich trägt zur Vollendung bei.",
    "Das größte Geschenk ist, die Schönheit in allem zu sehen.",
    "Die größte Weisheit liegt im Zuhören, nicht im Sprechen.",
    "Der Weg zur Erleuchtung beginnt mit der Selbsterkenntnis.",
    "Deine Gedanken formen deine Realität - denke positiv.",
    "Die größte Einsicht ist, dass wir alle miteinander verbunden sind.",
    "Die größte Herausforderung ist, im Hier und Jetzt zu leben.",
    "Deine Gedanken sind wie Samen - pflanze sie weise.",
    "Die beste Medizin ist ein fröhliches Herz.",
    "Die größte Schönheit liegt in der Einfachheit.",
    "Erfolg ist, wenn du im Einklang mit deinen Werten lebst.",
    "Wahre Stärke liegt im Vergeben, nicht im Vergelten.",
    "Das größte Geschenk ist die Liebe, die wir teilen.",
    "In der Dunkelheit finden wir das Licht.",
    "Das Leben ist eine Reise zu deinem wahren Selbst.",
    "Deine Gedanken sind der Anfang von allem.",
    "Das größte Abenteuer liegt in dir selbst.",
    "Die größte Freude liegt im Geben, nicht im Nehmen.",
    "Die beste Zeit für einen Neuanfang ist jetzt.",
    "Nichts ist kostbarer als deine Zeit - nutze sie weise.",
    "Erfolg ist, wenn du anderen ein Vorbild bist.",
    "Das Leben ist wie ein Fahrrad. Man muss sich vorwärts bewegen, um das Gleichgewicht nicht zu verlieren.",
    "Ich kann alles, außer Hochdeutsch.",
    "Warum bin ich Single? Weil ich die Spezial-Edition bin, nicht jeder kann das verkraften.",
    "Früher war alles besser, sogar die Zukunft.",
    "Wenn Plan A nicht funktioniert, mach dir keine Sorgen, das Alphabet hat noch 25 andere Buchstaben.",
    "Ich rede nicht viel, ich denke nur laut.",
    "Ich trinke Fanta, damit ich Fantasie bekomme.",
    "Werde erwachsen, haben sie gesagt. Es wird Spaß machen, haben sie gesagt.",
    "Ich habe heute keine Zeit für Stress, ich muss noch den Unsichtbaren anrufen.",
    "Mein Therapeut sagt, ich soll die Menschen so nehmen, wie sie sind, aber das will ich nicht.",
    "Warum aufhören zu träumen, wenn du aufwachen kannst und alles ruinieren?",
    "Zu spät kommen ist in Wirklichkeit mein Superpower. Ich bin immer genau zur falschen Zeit am richtigen Ort.",
    "Ich bin nicht faul, ich bin im Energiesparmodus.",
    "Wenn manche Menschen zu viel reden würden, hätten sie nichts mehr zu sagen.",
    "Mein Computer hat mich noch nie gefragt, ob ich wirklich sicher bin.",
    "Ich weiß nicht, was deprimierender ist: der Montag oder mein Wecker.",
    "Ich kann alles, außer Körbe werfen.",
    "Ein Tag ohne Sonnenschein ist wie, weißt du, Nacht.",
    "Ich werde erwachsen, aber nicht heute.",
    "Ich tanke Kaffee, damit ich die Gespräche in meinem Kopf schneller hören kann.",
    "Ich habe eine Diät gemacht, aber sie hat mich nicht gesucht.",
    "Ich trinke nie Wasser. Die Fische darin pinkeln doch.",
    "Ich bin nicht dick, meine Schönheit ist im Überfluss.",
    "Ich habe keine Macken! Das sind Special Effects.",
    "Ich rede nicht mit mir selbst, ich brauche nur eine kompetente Beratung.",
    "Die Schwerkraft ist schuld, dass ich auf der Couch festklebe.",
    "Früher dachte ich, ich sei schüchtern. Heute weiß ich, dass ich nur nicht jeden Treffpunkt brauche.",
    "Ich bin so toll, selbst meine Fehler sind perfekt.",
    "Scheitern ist auch Erfahrung.",
    "Manchmal glaube ich, meine Seele ist ein Gelee mit Bauchansatz.",
    "Der frühe Vogel kann mich mal.",
    "Geld allein macht nicht glücklich. Man muss es schon ausgeben können.",
    "Ich habe keine Zeit, mich zu beeilen.",
    "Ich möchte zurück in eine Zeit, als ich dachte, Tomaten sind Gemüse und nicht Lügen der Regierung.",
    "Ich werde nicht älter, ich werde erfahrener.",
    "Ich bin nicht langsam. Ich genieße nur die Reise.",
    "Ich bin so gechillt, ich würde mir sogar Zeitreisen leisten können.",
    "Lebe jeden Tag so, als ob deine WiFi-Verbindung schwach ist.",
    "Ich hatte eine brillante Idee, aber mein Goldfisch hat mich abgelenkt.",
    "Ein Kühlschrank ist ein Kaltblüter.",
    "Ich falle nicht, ich tanze nur mit der Schwerkraft.",
    "Meine Superkraft? Unbegrenzte Geduld, aber beeil dich!",
    "Ich bin nicht faul, ich bin im Energiesparmodus.",
    "Ich bin ein Abenteurer in einem Paralleluniversum, der versucht, in dieser Welt zu überleben.",
    "Wenn ich du wäre, wäre ich eifersüchtig auf mich.",
    "Ich arbeite hart, damit mein Hund ein besseres Leben haben kann.",
    "Kaffee, weil Erwachsen sein hart ist.",
    "Ich wäre ein super Modell, aber ich esse zu gerne.",
    "Manche nennen es faul, ich nenne es Energie sparen für Wichtigeres.",
    "Meine Superkraft? Prokrastinieren bis zur letzten Sekunde.",
    "Ich weiß, ich bin nicht perfekt, aber ich bin so nah dran, dass es gruselig ist.",
    "Ich habe eine Lese-Rechtschreib-Schwäche. Ich lese und schreibe, was ich will.",
    "Ich bin eine To-Do-Liste, die nie endet.",
    "Ich liebe es, mit Menschen zu arbeiten, aber nicht mit ihnen zu reden.",
    "Schokolade löst keine Probleme, aber das tut ein Apfel auch nicht.",
    "Die Ironie meines Lebens: Ich bekomme immer die besten Ideen, wenn ich nicht arbeiten kann.",
    "Manchmal bin ich zu clever für mich selbst.",
    "Der Wecker ist mein größter Feind und mein bester Freund zugleich.",
    "Ich habe keine Probleme, nur versteckte Talente.",
    "Wenn man bedenkt, wie oft ich irgendetwas mache, bin ich ein erstaunlich produktives Mitglied der Gesellschaft.",
    "Ich bin kein Faulpelz, ich bin im Energiesparmodus.",
    "Meine Eltern sagen immer: Geld ist nicht alles. Stimmt, aber es ist auch nicht nichts!",
    "Ich mag Menschen. Manche mag ich sogar sehr.",
    "Ich bin nicht alt. Ich bin nur länger jung als andere.",
    "Arbeit? Ich dachte, wir hätten Kuchen!",
    "Kreativität ist, wenn der Verstand Tanzen geht.",
    "Ich liebe es, Früh aufzustehen, um den Sonnenaufgang zu sehen, wenn er in den Nachrichten gezeigt wird.",
    "Ich spreche fließend Ironie.",
    "Ich habe keine Zeit für schlechte Laune. Ich kaufe mir lieber was Schönes."
]

const influencerZitate = [
    "Damage ist auf jeden Fall besser als Schaden auf Darius!",
    "Ohmzerstörer ist OP! Leider gibt es das Item nicht mehr, sehr Schade.",
    "YIIIII! STIIIIIIILLLLLL! THE MAIIIIIIIIIIIIN!",
    "Ich habe dich bei mir aufgenommen, hier in Dorsten!",
    "Weißt du wann mein Löwenkind Pulli ankommt?",
    "HAST DU DEZIBEL BESTELLT, ER IST JETZT DA!",
    "Ein Ei, 4 Zigaretten, eine Ibuprofen, dazu ein Rosinenbrötchen mit Leberwurst und dann kommt eine Kulinarische Linie ins Spiel.",
    "Guten Morgen, das ist ja gestern nicht so gut gelaufen, aber lass dich dadurch nicht entmutigen. Dann mal alle ab an die Arbeit.",
    "Man wendet sich nicht gegen den Rose.",
    "Mitfahrgelegenheit gesucht? Kutcher.de führ schnelle Mitfahrgelegenheiten durch ganz Deutschland. HÜAH!",
    "Süßes sonst geb ich dir Süßes.",
    "Ro. Ro. Ro. Rosin! Lover of the kitchen queen!",
    "Einmal bitte EINSTEIGEN! In den Lovetrain.",
    "Du BEEP BEEP. Du BEEP BEEP Stück BEEP. Der springt invis auf mich drauf. Wie willst du denn vorher exhausten? Der ist INVIS vorher. Hast du nen Röntgenblick? Bist du Superman? Du bist SuperBEEPjunge.",
    "Sei wie ein Chama Leon: Immer anpassungsfähig.",
    "Wießt du wie man an dieses Playbook herankommt? Ich habe nicht sonderlich viel Erfolg bei Frauen.",
    "In meinem Körper, wo eigentlich die Schamdrüse ist, gibt es noch eine weitere ich-find's-scharf-Drüse. Wirklich wahr!",
    "Selbst wenn man manchmal weiß wie das Ziel aussieht, bedeutet das nicht, dass die Reise dorthin nicht Spaß machen kann.",
    "Ein Buch ist ein Spiegel, wenn ein. OH VERDAMMT. DA KOMMT GIOVANNI MIT DER MEXINAKANISCHEN MAFIA! SCHNELL! RENN!",
    "Mögest du niemals so schlechte Witze machen und Serien empfehlen wie Shantao. Der ist wirklich das Letzte.",
    "Na gut, na gut. Dann quit game. Quit it. Kommt alle in Diamond, kommt. Wer muss morgen zur Schule? Hand Hoch. Ähm, ich muss nicht zur Schule. Du nicht, du hast morgen frei. Papa Frank sagt: \"Du gehst morgen schön Elo Pumpen!\". Hast du ne Freundin? Bald ni` mehr. Die stört nur beim Zocken.",
    "Vielleicht bist du derjenige, der Kutcher überreden kann Elden Ring zu spielen.",
    "Ich werd mein nächstes Haustier nach dir benenen"
]

const leagueWits = [
    "Von Malphite kann man lernen, wie man feste Prinzipien hat.",
    "Den Teufel malen, aber Yuumi anbeten.",
    "Schon im Morgengrauen singt der Hahn - aber nicht vor Swain.",
    "Ein Blitz kann nicht zweimal in dasselbe Ekko schlagen.",
    "Der frühe Kassadin fängt den Wurm.",
    "Wenn du Zoe bittest, holt sie dir die Sterne vom Himmel.",
    "Im Zweifel für den Trundle.",
    "Gut Ding will Udyr haben.",
    "Die Felle davonschwimmen sehen, wie Urf auf hoher See.",
    "Der Teemo im Porzellanladen.",
    "Wo Urgot geht, wächst kein Gras mehr.",
    "Jax-All-Trades, Meister von keins.",
    "Immer auf Achse sein, wie Rammus.",
    "Wo Urgot geht, wächst kein Gras mehr.",
    "Mit zwei Nasus zählt man doppelt.",
    "Rede nicht, wenn Sejuani spricht.",
    "In der Ruhe liegt die Shen.",
    "Nicht alle Blitze sind von Kennen.",
    "Zu früh gefreut, sagte Ekko.",
    "Brauchst du einen Rat? Frag Twitch!",
    "Wer viel Riven hat, hat auch viel zu verlieren.",
    "Mit Bard fängt man keine Alistar.",
    "Manchmal musst du einfach 'n Braum sein und durch.",
    "Nachts sind alle Yordles grau.",
    "Fühle den Rhythmus des Herzschlags - Sona.",
    "Wer zu spät kommt, den bestraft Malzahar.",
    "Wenn das Leben dir Zitronen gibt, wirf sie zurück - Zyra.",
    "Eile mit Weile, sagte Master Yi.",
    "Bäume haben Ohren, aber Maokai hört nicht zu.",
    "Leben wie ein Jax im Busch.",
    "Wo Yasuo geht, wächst kein Gras.",
    "Hochmut kommt vor dem Fall, besonders bei Camille.",
    "Es regnet Katzen und Hunde, sagte Lulu und verwandelte Nasus.",
    "Aufgeschoben ist nicht aufgehoben, sagte Zilean.",
    "Jeder ist seines Kha'Zix' Schmied.",
    "Nicht alle Sterne gehören Azir.",
    "Das Leben ist kein Ponyhof, aber manchmal ein Hecarim-Rennen.",
    "Die Nacht ist nicht dunkel, wenn Nocturne lacht.",
    "Ein Fiddlesticks in der Kehle.",
    "Auf dem falschen Fuß erwischt, wie bei Rengar in der Botlane.",
    "Die dümmsten Bauern haben die größten Garen.",
    "Schlafende Hunde sollst du wecken, aber nicht Nasus.",
    "Der letzte Biss, wie bei Tahm Kench im 1v1.",
    "Jeder ist seines Rengars Schmied.",
    "Nicht alle Sterne gehören Azir.",
    "Das Leben ist kein Ponyhof, aber manchmal ein Hecarim-Rennen.",
    "Die Nacht ist nicht dunkel, wenn Nocturne lacht.",
    "Ein Fiddlesticks in der Kehle.",
    "Die dümmsten Bauern haben die größten Garen.",
    "Schlafende Hunde sollst du wecken, aber nicht Nasus.",
    "Wer im Glashaus sitzt, sollte keine Steine werfen - außer Anivia.",
    "Die Welt steht dir offen, wie Zileans Chronoshift.",
    "Wie ein Blitz aus heiterem Himmel, wie Kennen im Teamfight.",
    "Eulen nach Athen tragen und Nami auf die Bot Lane.",
    "In der Ruhe liegt die Zed.",
    "Nichts ist in Stein gemeißelt, außer bei Malphite.",
    "Der frühe Hecarim fängt den Teemo.",
    "Alle sieben Nidas sind eine Kiste wert.",
    "Über den Wolken muss die Freiheit wohl grenzenlos sein, wie bei Quinn und Valor.",
    "Gut Ding will Udyr haben.",
    "In der Kürze liegt die Quinn.",
    "Die Ruhe vor dem Sturm, wie vor einem Kled-Engage.",
    "Hoffen und Bangen, wie ein ADC im Teamfight.",
    "Wer zu spät kommt, den bestraft Malzahar.",
    "Schönheit liegt im Auge des Betrachters - und manchmal im Schwung von Ahri's Orb.",
    "Viele Wege führen nach Rom, aber nur einer nach Teemo's Pilzfeld.",
    "Ein Krieger, ein Schwert, eine Bestimmung - Riven.",
    "Eile mit Weile, sagte Master Yi.",
    "Nicht den Kopf in den Sand stecken, sondern Rammus nachmachen und losrollen.",
    "Wenn du in ein Loch fällst, baue einen Tunnel - Rek'Sai.",
    "Macht ist wie ein Fluss - Swain beherrscht ihn.",
    "Ein Hingucker sein, wie ein schöner Lux-Laser.",
    "Ein Krieger ohne Zweifel, wie Garen ohne R.",
    "Das Glück ist mit den Mutigen - und mit Miss Fortune.",
    "Besser spät als nie - aber Jhin sagt: Besser pünktlich und präzise.",
    "Klugheit ist eine Blume, die in jedem Boden blüht - wie Malzahars E.",
    "Morgenstund hat Lux im Mund.",
    "Ein Tropfen auf den heißen Shaco.",
    "Immer mit der Ruhe, sagte Bard und sammelte seine Meeps.",
    "Vom Regen in die Drizzle, wie bei Gnar's Transformation.",
    "Klappe zu, Teemo tot.",
    "Lieber den Spatz in der Hand, als den Fiddle im Busch.",
    "Wo Rauch ist, da ist auch Brand, wie bei Brand's Ulti.",
    "Ein Jinx im Karton.",
    "Man soll den Tag nicht vor dem Udyr loben.",
    "Zwei Nasus sind besser als einer.",
    "Wenn der Lee Sin mit dem Teemo tanzt.",
    "Einmal Lee Sin, immer Lee Sin.",
    "Wer den Schaden hat, braucht für den Spott nicht zu sorgen - sagt Draven.",
    "Einmal Rammus, immer Rammus.",
    "Nicht alle Skarner sind Felsen.",
    "Die Geister, die ich rief, wird nicht los - Yorick.",
    "Besser spät mit der Fähre, als nie am Twisted Fate.",
    "Vom Regen in die Janna.",
    "Ein wahrer Meister Yasuo's ist nie ein Opfer, sondern immer ein Rivale.",
    "Einen Stein im Brett haben, wie Malphite im Team.",
    "Ein Lulu in der Hand ist besser als zwei im Busch.",
    "Die Guten ins Kröpfchen, die Schlechten ins Kröpfchen - Tahm Kench.",
    "Wer zuletzt lacht, lacht am besten, wie Draven im Pentakill.",
    "Mit einem Lächeln im Gesicht, wie bei Jhin nach einem gelungenen Ulti.",
    "Mit einem Zwinkern und einem Lulu auf der Bot Lane.",
    "Das ist wie Eulen nach Athen tragen, sagte Fiddlesticks in der Nacht.",
    "Wer im Glashaus sitzt, sollte nicht mit Felsen werfen - es sei denn, es ist Malphite.",
    "Ein Teemo im Porzellanladen.",
    "Besser spät als nie - aber Jhin sagt: Besser pünktlich und präzise.",
    "Klein, aber oho - wie ein Yordle in der Schlacht.",
    "Ein Dorn im Auge sein, wie ein Teemo im gegnerischen Dschungel.",
    "Die beste Verteidigung ist ein guter Angriff - aber auch ein guter Braum.",
    "Vom Winde verweht, wie Yasuo's Gegner nach seinem Tornado.",
    "Ein Leben wie ein Aufstieg, wie das von Kayle.",
    "Das schwarze Schaf sein, wie ein Fiddlesticks im Baron-Pit.",
    "Wer nicht wagt, der nicht gewinnt - außer bei Wukong im Teamfight.",
    "Die Würfel sind gefallen, sagte Twisted Fate vor seinem Ulti.",
    "Auf den Busch klopfen, wie Rek'Sai auf der Rift.",
]

var url = new URL(window.location.href);
var params = new URLSearchParams(url.search);
const id = params.get('id');
const frankRedetGif = document.getElementById('frankDiv');

const rosinVoiceSettings = {
    similarity_boost: 0.02,  // Ändere die Similarity Boost (beachte den zulässigen Bereich)
    stability: 0.95,  // Ändere die Stability (beachte den zulässigen Bereich)
    style: 0,  // Ändere den Style (beachte den zulässigen Bereich)
    use_speaker_boost: true  // Nutze Speaker Boost (true/false)
};

var socket;

function connectWebSocket() {
    socket = new WebSocket(`wss://rosin-bingo.glitch.me?id=${id}`);
    socket.pingTimeout = 315360000000; // 10 years in milliseconds

    socket.onopen = function () {
        console.log('WebSocket-Verbindung hergestellt.');
    };

    socket.onclose = function () {
        console.log('WebSocket-Verbindung geschlossen. Versuche erneut zu verbinden...');
        connectWebSocket(); // Verbindung nach 2 Sekunden erneut aufbauen
    };

    socket.onerror = function (error) {
        console.error('WebSocket-Fehler aufgetreten: ', error);
    };

    socket.onmessage = function (event) {
        const message = event.data;
        console.log(message);

        const randomLebensWeisheit = generateWisdom();
        const data = JSON.parse(message)

        var textToSpeech;

        if (data.text.startsWith("Danke") || data.text === "") {
            textToSpeech = data.text + randomLebensWeisheit;
        } else {
            textToSpeech = data.text;
        }

        const headers = {
            "xi-api-key": data.api_key,
            "Content-Type": "application/json"
        };

        const requestBody = JSON.stringify({
            text: textToSpeech,
            voice_settings: rosinVoiceSettings,
            model_id: "eleven_multilingual_v2"
        });

        const response = fetch(`https://api.elevenlabs.io/v1/text-to-speech/${data.voiceID}`, {
            method: 'POST',
            headers: headers,
            body: requestBody
        })
            .then(res => res.blob())
            .then(blob => {
                const url = URL.createObjectURL(blob);
                const audio = new Audio(url);

                audio.addEventListener('play', () => {
                    frankRedetGif.style.backgroundImage = "url(\"../resources/FrankRedet.gif\")";
                });

                audio.addEventListener('ended', () => {
                    frankRedetGif.style.backgroundImage = "url(\"../resources/Frankstopp.png\")";
                    const msg = id + "<audioended";
                    socket.send(msg);
                });

                audio.play();

            });
    };
}

function generateWisdom() {
    var wisdomArray;
    const random = Math.random();
    if (random < 0.08) {
        wisdomArray = influencerZitate;
    } else if (random > 0.5) {
        wisdomArray = leagueWits;
    } else {
        wisdomArray = lebensWeisheiten;
    }
    const randomIndex = Math.floor(Math.random() * wisdomArray.length);
    return wisdomArray[randomIndex];
}

// Initialer Verbindungsaufbau
connectWebSocket();